import test from "node:test";import assert from "node:assert/strict";import { FACTOR_SET_SCHEMA_VERSION, FACTOR_SET_SLOTS, emptySlots, validateFactorSetDraft, createFactorSet } from "../assets/js/library/factor-set.js";
const entry=(id,c)=>[id,{id,characterId:c}];
const validate=(assign,trainee=null)=>{const entries=new Map(Object.entries(assign).map(([slot,c])=>entry(slot,c)));const slots=emptySlots();Object.keys(assign).forEach(slot=>slots[slot]=slot);return validateFactorSetDraft(slots,entries,trainee);};
test("FactorSet has six stable slots and schema v2",()=>{assert.equal(FACTOR_SET_SCHEMA_VERSION,2);assert.deepEqual(FACTOR_SET_SLOTS.map(x=>x.key),["parentA","grandparentA1","grandparentA2","parentB","grandparentB1","grandparentB2"]);assert.equal(Object.keys(emptySlots()).length,6);});
test("FactorSet rejects only lineage-invalid duplicate base characters",()=>{assert.equal(validate({parentA:"c1",parentB:"c1"}).valid,false);assert.equal(validate({parentA:"c1",grandparentA1:"c1"}).valid,false);assert.equal(validate({parentA:"c1",grandparentA2:"c1"}).valid,false);assert.equal(validate({parentB:"c1",grandparentB1:"c1"}).valid,false);assert.equal(validate({parentB:"c1",grandparentB2:"c1"}).valid,false);});
test("FactorSet allows cross-line duplicates but rejects same-line grandparent duplicates",()=>{assert.equal(validate({parentA:"c1",grandparentB1:"c1"}).valid,true);assert.equal(validate({parentB:"c1",grandparentA1:"c1"}).valid,true);assert.equal(validate({grandparentA1:"c1",grandparentA2:"c1"}).valid,false);assert.equal(validate({grandparentB1:"c1",grandparentB2:"c1"}).valid,false);assert.equal(validate({grandparentA1:"c1",grandparentB1:"c1"}).valid,true);});
test("optional trainee conflicts with parents but may match grandparents",()=>{assert.equal(validate({parentA:"c1"},{characterId:"c1"}).valid,false);assert.equal(validate({parentB:"c1"},{characterId:"c1"}).valid,false);assert.equal(validate({grandparentA1:"c1"},{characterId:"c1"}).valid,true);assert.equal(validate({grandparentB2:"c1"},{characterId:"c1"}).valid,true);});
test("FactorSet requires a name and preserves createdAt while editing",()=>{const entries=new Map([entry("a","c1")]);const slots={...emptySlots(),parentA:"a"};assert.throws(()=>createFactorSet({id:"set_1",name:"",slots,entriesById:entries}),/編成名は必須/);const set=createFactorSet({id:"set_1",name:"test",slots,entriesById:entries,trainee:{characterId:"c2",variantId:"v2",nameSnapshot:"B"},createdAt:"2026-10-05T00:00:00.000Z",now:"2026-10-06T00:00:00.000Z"});assert.equal(set.createdAt,"2026-10-05T00:00:00.000Z");assert.equal(set.updatedAt,"2026-10-06T00:00:00.000Z");assert.equal(set.trainee.characterId,"c2");});

test("FactorSet UI uses two lineage columns, assignment badges, and edit/new-save flow",async()=>{const fs=await import("node:fs/promises");const source=await fs.readFile(new URL("../assets/js/library/factor-set-dialog.js",import.meta.url),"utf8");assert.match(source,/factor-set-assigned-badge/);assert.doesNotMatch(source,/class="ghost-button use">セット/);assert.match(source,/factor-set-save-new/);assert.match(source,/factor-set-save-changes/);assert.match(source,/editingId=set\.id/);assert.match(source,/savedSnapshot=draftSnapshot\(\)/);assert.match(source,/保存していない変更があります/);});
test("saved FactorSet filters separate trainee and inherited characters and include tags and factors",async()=>{const fs=await import("node:fs/promises");const source=await fs.readFile(new URL("../assets/js/library/factor-set-dialog.js",import.meta.url),"utf8");assert.match(source,/factor-set-saved-trainee/);assert.match(source,/factor-set-saved-inherited/);assert.match(source,/inheritedCharacterId/);assert.match(source,/factor-set-saved-tags/);assert.match(source,/factor-set-saved-factor-search/);assert.match(source,/factor-set-saved-factor-mode/);});
